-- schema.sql: estrutura das tabelas conforme especificação

-- =========================
-- A) Estruturantes
-- =========================
create table if not exists tel_localidade (
  incdlocalidade      int generated by default as identity primary key,
  txnomelocalidade    varchar(45) not null
);

create table if not exists tel_departamento (
  incddepartamento    int generated by default as identity primary key,
  departamento        varchar(45) not null
);

create table if not exists tel_rel_dept_rh (
  incdreldeptrh       int generated by default as identity primary key,
  depto_rh_codigo     int not null,
  incddepartamento    int not null references tel_departamento(incddepartamento)
);

-- =========================
-- B) Léxico/Validações de Contato
-- =========================
create table if not exists tel_ref_origem_contato (
  incdreforigcont     int generated by default as identity primary key,
  descricao           varchar(30) not null,
  formato             varchar(20) not null
);

create table if not exists tel_origem_contato (
  incdorigemcontato   int generated by default as identity primary key,
  tipo                varchar(45) not null,
  origem              varchar(45) not null
);

create table if not exists tel_tipo_contato (
  incdtipocontato     int generated by default as identity primary key,
  tipo                varchar(30) not null,
  descricao           varchar(30)
);

-- =========================
-- C) Identidades, Permissões e Grupos
-- =========================
create table if not exists idp_usuario (
  idp_user_id         varchar(64) primary key,
  colaborador_username varchar(12) unique not null,
  nome_exibicao       varchar(60)
);

create table if not exists tel_grupo_permissao (
  incdgrupo           int generated by default as identity primary key,
  grupo               varchar(40) not null
);

create table if not exists tel_grupo_membro (
  incdgrupo           int references tel_grupo_permissao(incdgrupo) on delete cascade,
  idp_user_id         varchar(64) references idp_usuario(idp_user_id) on delete cascade,
  incddepartamento    int references tel_departamento(incddepartamento),
  incdlocalidade      int references tel_localidade(incdlocalidade),
  primary key (incdgrupo, idp_user_id, incddepartamento, incdlocalidade)
);

create table if not exists tel_permissao_view (
  idp_user_id         varchar(64) not null,
  incddepartamento    int,
  incdlocalidade      int,
  generated_at        timestamp default now()
);

-- =========================
-- D) Cadastros de Pessoas/Contatos
-- =========================
create table if not exists tel_contato (
  incdcontato         int generated by default as identity primary key,
  nome                varchar(40) not null,
  origem              varchar(30) not null,
  matricula           int not null,
  incddepartamento    int not null references tel_departamento(incddepartamento),
  incdlocalidade      int not null references tel_localidade(incdlocalidade),
  status              char(2) not null check (status in ('At','In')),
  preferencia         varchar(50),
  unique (nome, incddepartamento, incdlocalidade, origem)
);

create table if not exists tel_contato_meio (
  incdcontatomeio     bigserial primary key,
  incdcontato         int not null references tel_contato(incdcontato) on delete cascade,
  incdtipocontato     int not null references tel_tipo_contato(incdtipocontato),
  valor               varchar(100) not null
);

create table if not exists tel_responsavel (
  incdrespdepart      int generated by default as identity primary key,
  incdcontato         int not null references tel_contato(incdcontato),
  idp_user_id         varchar(64) not null references idp_usuario(idp_user_id),
  incddepartamento    int not null references tel_departamento(incddepartamento),
  incdlocalidade      int not null references tel_localidade(incdlocalidade)
);

-- =========================
-- E) Sites de Busca
-- =========================
create table if not exists tel_site_busca (
  incdsite            int generated by default as identity primary key,
  site                varchar(100) not null,
  url                 varchar(100) not null
);

-- Índice para Tela de Navegação
create index if not exists ix_nav_contato on tel_contato (nome, incddepartamento, incdlocalidade, origem);
