name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build backend
        run: |
          cd api
          cargo build --locked --verbose
      - name: Run cargo audit
        run: |
          cd api
          cargo install cargo-audit || true
          cargo audit || true
      - name: Build frontend
        run: |
          cd frontend
          npm ci
          npm run build || true
